"""add batch_id and batch_name to published_schedule

Revision ID: 3688774fc4a7
Revises: c5ae2e6ab388
Create Date: 2026-09-11 11:31:49.649286

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3688774fc4a7'
down_revision: Union[str, None] = 'c5ae2e6ab388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_schedule', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.add_column('published_schedule', sa.Column('batch_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_published_schedule_batch_id'), 'published_schedule', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_published_schedule_batch_id'), table_name='published_schedule')
    op.drop_column('published_schedule', 'batch_name')
    op.drop_column('published_schedule', 'batch_id')
    # ### end Alembic commands ###
